version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      LANG: C.UTF-8
      LANGUAGE: en_US

  php:
    build: docker/php
    container_name: php
    volumes:
      - ./:/var/www:cached
      - ~/.ssh:/root/.ssh
    environment:
      LANG: C.UTF-8
      LANGUAGE: en_US

  postgres:
    image: postgres:12.2
    container_name: db
    ports:
      - "5433:5432"
    volumes:
      - ./docker/php:/var/lib/postgres
      - ./docker/php/initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
